const assert = require('node:assert/strict');
const { plan, parse, at, overlaps } = require('../assets/js/planner-core.js');
const now = new Date('2026-10-08T08:00:00');
const preferences = { start: '09:00', end: '18:00', focus: 'morning' };
const task = (id, overrides = {}) => ({ id, title: id, duration: 60, deadline: '2026-10-08T18:00', priority: 'normal', done: false, ...overrides });
const fixed = [{ id: 'meeting', date: '2026-10-08', start: '10:00', end: '11:00' }];
const parsed = parse('明天下午5点前完成项目报告，需要2小时，高优先级', now);
assert.equal(parsed.duration, 120);
assert.equal(parsed.deadline, '2026-10-09T17:00');
assert.equal(parsed.priority, 'high');
assert.equal(parse('Finish tomorrow by 17:00, 1.5 hours, high priority', now).duration, 90);
assert.equal(parse('Review 2026-10-12 14:30, 45 min', now).deadline, '2026-10-12T14:30');
assert.equal(parse('Write a report', now).duration, 60);
const tasks = [task('normal'), task('urgent', { priority: 'high', duration: 120 }), task('done', { done: true })];
const before = JSON.stringify(tasks);
const result = plan(tasks, fixed, preferences, now);
assert.equal(JSON.stringify(tasks), before, 'Proposals must not mutate tasks');
assert.equal(result.issues.length, 0);
assert.equal(result.slots.length, 2);
assert.equal(result.slots.find(slot => slot.taskId === 'urgent').start, at('2026-10-08', '11:00'));
assert.equal(result.slots.find(slot => slot.taskId === 'normal').start, at('2026-10-08', '09:00'));
assert(!overlaps(result.slots[0], result.slots[1]), 'Tasks must not overlap');
for (const slot of result.slots) assert(!overlaps(slot, { start: at('2026-10-08', '10:00'), end: at('2026-10-08', '11:00') }), 'Fixed events must stay protected');
const afternoon = plan([task('a')], [], { ...preferences, focus: 'afternoon' }, now);
assert.equal(afternoon.slots[0].start, at('2026-10-08', '13:00'));
const earlyDeadline = plan([task('a', { deadline: '2026-10-08T11:00' })], [], { ...preferences, focus: 'afternoon' }, now);
assert.equal(earlyDeadline.slots[0].start, at('2026-10-08', '09:00'), 'Deadline must take precedence over habit');
const conflict = plan([task('large', { duration: 600 }), task('late', { deadline: '2026-10-07T18:00' })], [], preferences, now);
assert.equal(conflict.slots.length, 0);
assert.deepEqual(conflict.issues.map(issue => issue.reason).sort(), ['capacity', 'overdue']);
assert.equal(plan([task('a')], [], { start: '18:00', end: '09:00' }, now).issues[0].reason, 'hours');
const late = plan([task('a', { deadline: '2026-10-09T18:00' })], [], preferences, new Date('2026-10-08T17:45'));
assert.equal(late.slots[0].start, at('2026-10-09', '09:00'));
const original = plan([task('a'), task('b')], [], preferences, now);
const longer = plan([task('a', { duration: 90 }), task('b')], [], preferences, now);
assert.equal(original.slots[1].start, at('2026-10-08', '10:00'));
assert.equal(longer.slots[1].start, at('2026-10-08', '10:30'), 'Extending a task must shift the following task');
console.log('PASS: bilingual extraction, priorities, deadlines, fixed events, focus preferences, overdue/capacity conflicts, completion, and dynamic replanning.');
